https:
  host: "0.0.0.0"
  port: "8082"
  basepath: "/api"
  
api:
  autodiscovery:
    id: "15664013"
        
tls:
  key-store:
    path: "SVMEmptyKeystore.jks"
    password: "Svm123"
    key:
      password: "Svm123"
      
mask:
  keylist: "['phone_number',  'RecordTypeId']"